export const TYPES = {
  FETCH_BOOKS_LIST_START: "FETCH_BOOKS_LIST_START",
  FETCH_BOOKS_LIST_SUCCESS: "FETCH_BOOKS_LIST_SUCCESS",
  FETCH_BOOKS_LIST_ERROR: "FETCH_BOOKS_LIST_ERROR",
  SET_FAVORITES_LIST: "SET_FAVORITES_LIST",
  SET_CURRENT_OPENED_BOOK: "SET_CURRENT_OPENED_BOOK",

  FETCH_AUTHOR_LIST_START: "FETCH_AUTHOR_LIST_START",
  FETCH_AUTHOR_LIST_SUCCESS: "FETCH_AUTHOR_LIST_SUCCESS",
  FETCH_AUTHOR_LIST_ERROR: "FETCH_AUTHOR_LIST_ERROR",
  SET_CURRENT_OPENED_AUTHOR: "SET_CURRENT_OPENED_AUTHOR",
  EXPAND_AUTHOR_MENU: "EXPAND_AUTHOR_MENU",
  CLOSE_AUTHOR_MENU: "CLOSE_AUTHOR_MENU",
};